pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'mite-recrafted'

// Include IronChests
include ':ironchests'
project(':ironchests').projectDir = file('submodules/IronChests')
